package dto;

import java.io.Serializable;

/*
DROP TABLE REVIEW
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_REVIEW;

CREATE TABLE REVIEW(
	NUM NUMBER(8) NOT NULL,
	
	ID VARCHAR2(50) NOT NULL,
	HOTELNAME VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(300) NOT NULL,
	
	SCORE NUMBER(10) NOT NULL,
	
	DEL NUMBER(1) NOT NULL,
	READCOUNT NUMBER(8) NOT NULL,
	REGDATE DATE NOT NULL
);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_NUM FOREIGN KEY(NUM)
REFERENCES RESERVE(SEQ);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_ID FOREIGN KEY(ID)
REFERENCES RESERVE(ID);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_HNAME FOREIGN KEY(HOTELNAME)
REFERENCES RESERVE(HOTELNAME);
*/

public class ReviewDto implements Serializable {

}
